project:
  type: website

website:
  title: "Almanac of US Politics"
  site-url: https://AlmanacOfUSPolitics.com
  repo-url: https://github.com/reuning/almanac_us_politics
  open-graph: true
  margin-footer: |
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
      <label class="form-check-label" for="flexSwitchCheckDefault">Interactive Plots</label>
    </div>
  sidebar:
    style: "floating"
    search: true
    contents:
      - about.qmd
      - section: "Voter Trends"
        contents:
          - voter_trends/party.qmd
          - voter_trends/ideology.qmd
          - section: Opinion
            contents: voter_trends/opinion/*
          - section: Political Activity
            contents: voter_trends/political_activity/*
          - section: Historical Trends
            contents: voter_trends/historic/*
  page-footer:
    center:
      - icon: github
        href: https://github.com/reuning/almanac_us_politics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: 
      - file: button.html
      - text: <script defer data-domain="almanacofuspolitics.com" src="https://plausible.io/js/script.js"></script>


execute:
  echo: false 
  warning: false 
